# permissions for end users to view virtualmachinerestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachinerestore-viewer-role
rules:
- apiGroups:
  - hci.wjyl.com
  resources:
  - virtualmachinerestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hci.wjyl.com
  resources:
  - virtualmachinerestores/status
  verbs:
  - get
