# permissions for end users to edit virtualmachinerestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachinerestore-editor-role
rules:
- apiGroups:
  - hci.wjyl.com
  resources:
  - virtualmachinerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hci.wjyl.com
  resources:
  - virtualmachinerestores/status
  verbs:
  - get
