# permissions for end users to view virtualmachinebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachinebackup-viewer-role
rules:
- apiGroups:
  - hci.wjyl.com
  resources:
  - virtualmachinebackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hci.wjyl.com
  resources:
  - virtualmachinebackups/status
  verbs:
  - get
